// generated by `rmsync pdf pull`; do not edit. Ink from the tablet, one SVG per annotated page.
#let widths = ("1": 63%, "2": 36%,)
#let has(n) = str(n) in widths
#let crop(n) = image("p" + str(n) + "-crop.svg", width: widths.at(str(n)))
#let full(n) = place(top + left, image("p" + str(n) + ".svg", width: 100%))

#let ink(body) = context {
  if sys.inputs.at("rmsync-ink", default: "yes") == "no" { body }
  else if target() == "html" {
    let page = state("rmsync-page", 1)
    show pagebreak: it => {
      context { let n = page.get(); if has(n) { crop(n) } }
      page.update(n => n + 1)
      it
    }
    body
    context { let n = page.get(); if has(n) { crop(n) } }
  } else {
    set page(background: context { let n = counter(page).get().first(); if has(n) { full(n) } })
    body
  }
}
