// generated by `rmsync pdf pull`; do not edit. Ink from the tablet, one SVG per annotated page.
#let ink(body) = if sys.inputs.at("rmsync-ink", default: "yes") == "no" { body } else {
  set page(background: context {
    let n = counter(page).get().first()
    if n in (1, 2) { place(top + left, image("p" + str(n) + ".svg", width: 100%)) }
  })
  body
}
